import type {
  ConditionSource,
  MachineQuery,
  RiskProfile,
  SearchCondition,
} from "./types";

export const profileDefaults = {
  balanced: {
    minMarketCap: "3,000억원",
    minTradingValue: "30억원",
    maxVolatility: "25%",
    rsiRange: "40~68",
    rsiCeiling: "68",
    volumeSpike: "130%",
    volumeAcceleration: "125%",
    shortReturn: "3%",
    recentReturnCap: "18%",
    maxIntradayRange: "8%",
    maxSharpDropDays: "3",
    maxDebtRatio: "200",
    minOperatingMargin: "3%",
    minRoe: "5%",
    maxDefensiveDrawdown: "-20%",
    maDistanceRange: "-5%~8%",
    pullbackReturnRange: "-6%~1%",
    pullbackRsiRange: "42~58",
    revenueGrowth: "5%",
    operatingGrowth: "0%",
    maxPer: "18",
    maxPbr: "1.8",
  },
  conservative: {
    minMarketCap: "7,000억원",
    minTradingValue: "70억원",
    maxVolatility: "18%",
    rsiRange: "42~62",
    rsiCeiling: "62",
    volumeSpike: "115%",
    volumeAcceleration: "115%",
    shortReturn: "0%",
    recentReturnCap: "10%",
    maxIntradayRange: "5%",
    maxSharpDropDays: "2",
    maxDebtRatio: "150",
    minOperatingMargin: "5%",
    minRoe: "8%",
    maxDefensiveDrawdown: "-15%",
    maDistanceRange: "-4%~6%",
    pullbackReturnRange: "-4%~0%",
    pullbackRsiRange: "44~55",
    revenueGrowth: "3%",
    operatingGrowth: "0%",
    maxPer: "15",
    maxPbr: "1.5",
  },
  aggressive: {
    minMarketCap: "1,000억원",
    minTradingValue: "20억원",
    maxVolatility: "35%",
    rsiRange: "45~76",
    rsiCeiling: "76",
    volumeSpike: "160%",
    volumeAcceleration: "145%",
    shortReturn: "5%",
    recentReturnCap: "28%",
    maxIntradayRange: "12%",
    maxSharpDropDays: "5",
    maxDebtRatio: "250",
    minOperatingMargin: "0%",
    minRoe: "3%",
    maxDefensiveDrawdown: "-28%",
    maDistanceRange: "-8%~12%",
    pullbackReturnRange: "-9%~3%",
    pullbackRsiRange: "40~64",
    revenueGrowth: "10%",
    operatingGrowth: "8%",
    maxPer: "28",
    maxPbr: "3.0",
  },
};

export type ProfileDefaults = (typeof profileDefaults)[RiskProfile];

type ConditionOptions = {
  easyDescription?: string;
  source?: ConditionSource;
  sourcePhrase?: string;
};

const numberFromText = (value: string) =>
  Number(value.replace(/,/g, "").replace(/[^0-9.-]/g, ""));

const percentFromText = (value: string) => numberFromText(value);

const krwFromEok = (value: string) => numberFromText(value) * 100_000_000;

const rangeFromText = (value: string) => {
  const [min, max] = value.split("~").map((item) => percentFromText(item));
  return { min, max };
};

export const condition = (
  id: string,
  category: SearchCondition["category"],
  label: string,
  metric: string,
  operator: string,
  value: string,
  reason: string,
  indicatorKey: string,
  machineQuery: MachineQuery,
  options: ConditionOptions = {},
): SearchCondition => ({
  id,
  category,
  label,
  metric,
  operator,
  value,
  display: `${metric} ${operator} ${value}`,
  reason,
  easyDescription: options.easyDescription ?? reason,
  source: options.source ?? "user_expression",
  sourcePhrase: options.sourcePhrase,
  indicatorKey,
  machineQuery,
});

export const buildLiquidityCondition = (defaults: ProfileDefaults) =>
  condition(
    "liquidity-trading-value",
    "liquidity",
    "거래 실행 필터",
    "20일 평균 거래대금",
    ">=",
    defaults.minTradingValue,
    "조건식 결과가 거래가 너무 얇은 구간에 몰리지 않도록 기본 유동성 기준을 둡니다.",
    "volume",
    {
      field: "avg_trading_value_20d_krw",
      operator: ">=",
      value: krwFromEok(defaults.minTradingValue),
      unit: "krw",
    },
  );

export const buildStabilityConditions = (
  defaults: ProfileDefaults,
  wantsShortTerm: boolean,
) => [
  condition(
    "stability-market-cap",
    "stability",
    "규모 안정성",
    "시가총액",
    ">=",
    defaults.minMarketCap,
    "안정감, 대형, 꾸준함 같은 표현을 기업 규모 기준으로 정리합니다.",
    "marketCap",
    {
      field: "market_cap_krw",
      operator: ">=",
      value: krwFromEok(defaults.minMarketCap),
      unit: "krw",
    },
  ),
  condition(
    "risk-volatility",
    "risk",
    "흔들림 제한",
    "60일 변동성",
    "<=",
    wantsShortTerm ? profileDefaults.aggressive.maxVolatility : defaults.maxVolatility,
    "가격 흔들림이 과한 구간을 줄여 사용자가 말한 안정감에 맞춥니다.",
    "volatility",
    {
      field: "volatility_60d_pct",
      operator: "<=",
      value: percentFromText(
        wantsShortTerm ? profileDefaults.aggressive.maxVolatility : defaults.maxVolatility,
      ),
      unit: "percent",
    },
  ),
];

export const buildMomentumConditions = (defaults: ProfileDefaults) => [
  condition(
    "momentum-volume-spike",
    "liquidity",
    "거래 활성도",
    "금일 거래량 / 20일 평균 거래량",
    ">=",
    defaults.volumeSpike,
    "관심이 늘어난 흐름을 거래량 변화로 표현합니다.",
    "volume",
    {
      field: "volume_today_to_avg_20d_pct",
      operator: ">=",
      value: percentFromText(defaults.volumeSpike),
      unit: "percent",
    },
  ),
  condition(
    "trend-short-return",
    "trend",
    "최근 흐름",
    "20일 상승률",
    ">=",
    defaults.shortReturn,
    "강한 흐름이나 단기 탄력이라는 표현을 최근 가격 흐름 조건으로 바꿉니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: ">=",
      value: percentFromText(defaults.shortReturn),
      unit: "percent",
    },
  ),
];

export const buildCoreTrendRiskConditions = (defaults: ProfileDefaults) => [
  condition(
    "trend-ma",
    "trend",
    "추세 정렬",
    "20일 이동평균선",
    ">",
    "60일 이동평균선",
    "단기 흐름이 중기 흐름보다 위에 있는지 확인해 조건의 방향성을 정리합니다.",
    "movingAverageAlignment",
    { field: "ma20", operator: ">", value: "ma60" },
  ),
  condition(
    "risk-rsi",
    "risk",
    "과열 구간 완화",
    "RSI(14)",
    "between",
    defaults.rsiRange,
    "흐름의 강도를 보되 한쪽으로 과하게 쏠린 구간을 줄이기 위한 보조 조건입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "between",
      ...rangeFromText(defaults.rsiRange),
      unit: "ratio",
    },
  ),
];

export const buildGrowthConditions = (defaults: ProfileDefaults) => [
  condition(
    "growth-revenue",
    "growth",
    "매출 흐름",
    "최근 분기 매출 증가율",
    ">=",
    defaults.revenueGrowth,
    "성장이나 실적 개선이라는 표현을 매출의 방향성으로 정량화합니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.revenueGrowth),
      unit: "percent",
    },
  ),
  condition(
    "growth-operating-profit",
    "growth",
    "이익 흐름",
    "최근 분기 영업이익 증가율",
    ">=",
    defaults.operatingGrowth,
    "사업 성과가 함께 개선되는지를 별도 조건으로 확인합니다.",
    "fundamentals",
    {
      field: "operating_profit_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.operatingGrowth),
      unit: "percent",
    },
  ),
];

export const buildValueConditions = (defaults: ProfileDefaults) => [
  condition(
    "valuation-per",
    "valuation",
    "이익 대비 가격 부담",
    "PER",
    "<=",
    defaults.maxPer,
    "가격 부담이 낮은 편이라는 표현을 이익 대비 가격 기준으로 바꿉니다.",
    "valuation",
    {
      field: "per",
      operator: "<=",
      value: numberFromText(defaults.maxPer),
      unit: "ratio",
    },
  ),
  condition(
    "valuation-pbr",
    "valuation",
    "자산 대비 가격 부담",
    "PBR",
    "<=",
    defaults.maxPbr,
    "자산 기준에서 과도하게 높지 않은 구간을 찾는 조건입니다.",
    "valuation",
    {
      field: "pbr",
      operator: "<=",
      value: numberFromText(defaults.maxPbr),
      unit: "ratio",
    },
  ),
];

export const buildTrendDistanceConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-bollinger-inside",
    "risk",
    "밴드 내부 유지",
    "종가 위치",
    "inside",
    "볼린저밴드(20,2) 상단~하단",
    "평균 범위에서 과하게 벗어난 구간을 줄이기 위한 조건입니다.",
    "bollingerBand",
    { field: "close", operator: "insideBand", band: "bollinger_20_2" },
  ),
  condition(
    "phrase-ma-distance",
    "risk",
    "평균 대비 이격 제한",
    "20일 이동평균선 이격도",
    "between",
    defaults.maDistanceRange,
    "현재 가격이 기준 평균에서 지나치게 멀어지지 않았는지 확인합니다.",
    "maDistance",
    {
      field: "ma20_distance_pct",
      operator: "between",
      ...rangeFromText(defaults.maDistanceRange),
      unit: "percent",
    },
  ),
  condition(
    "phrase-rsi-ceiling",
    "risk",
    "RSI 상한",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "흐름 강도가 한쪽으로 과하게 쏠린 구간을 줄이기 위한 조건입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
];

export const buildOverheatAvoidanceConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-recent-return-cap",
    "risk",
    "최근 상승률 제한",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "짧은 기간에 가격 변화가 과해진 구간을 줄이기 위한 조건입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-overheat-rsi-cap",
    "risk",
    "과열 강도 제한",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "가격 흐름의 강도가 과하게 높은 구간을 줄입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-bollinger-upper-limit",
    "risk",
    "상단 이탈 제한",
    "종가 / 볼린저밴드 상단",
    "<=",
    "102%",
    "밴드 상단을 과하게 벗어난 구간을 제외하는 조건입니다.",
    "bollingerBand",
    {
      field: "close_to_bollinger_upper_pct",
      operator: "<=",
      value: 102,
      unit: "percent",
    },
  ),
];

export const buildVolumeStrengthConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-volume-acceleration",
    "liquidity",
    "최근 거래량 증가",
    "5일 평균 거래량 / 20일 평균 거래량",
    ">=",
    defaults.volumeAcceleration,
    "최근 거래가 이전 평균보다 늘어나는지 확인합니다.",
    "volume",
    {
      field: "avg_volume_5d_to_20d_pct",
      operator: ">=",
      value: percentFromText(defaults.volumeAcceleration),
      unit: "percent",
    },
  ),
  condition(
    "phrase-short-ma-break",
    "trend",
    "단기 흐름 전환",
    "5일 이동평균선",
    ">=",
    "20일 이동평균선",
    "짧은 흐름이 중기 흐름 위로 올라오는지 확인합니다.",
    "movingAverage",
    { field: "ma5", operator: ">=", value: "ma20" },
  ),
  condition(
    "phrase-macd-turn",
    "trend",
    "MACD 전환 확인",
    "MACD 히스토그램",
    ">=",
    "0",
    "단기 흐름의 힘이 이전보다 붙는지 보는 보조 조건입니다.",
    "macd",
    { field: "macd_histogram", operator: ">=", value: 0, unit: "ratio" },
  ),
];

export const buildStableUptrendConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-stable-uptrend-ma-alignment",
    "trend",
    "중기 추세 유지",
    "20일 이동평균선",
    ">=",
    "60일 이동평균선",
    "단기 평균 흐름이 중기 평균 흐름 아래로 밀리지 않는지 확인합니다.",
    "movingAverageAlignment",
    { field: "ma20", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-stable-uptrend-ma-slope",
    "trend",
    "중기선 기울기",
    "60일 이동평균선 기울기",
    ">",
    "0",
    "중기 기준선 자체가 아래로 꺾이지 않고 있는지 확인합니다.",
    "movingAverageSlope",
    {
      field: "ma60_slope_20d",
      operator: ">",
      value: 0,
      unit: "ratio",
    },
  ),
  condition(
    "phrase-stable-uptrend-60d-return",
    "trend",
    "최근 흐름",
    "60일 상승률",
    ">",
    "0%",
    "중기 기간의 가격 흐름이 위쪽 방향을 유지하는지 확인합니다.",
    "recentReturn",
    {
      field: "return_60d_pct",
      operator: ">",
      value: 0,
      unit: "percent",
    },
  ),
  condition(
    "phrase-stable-uptrend-volatility",
    "risk",
    "변동성 제한",
    "60일 변동성",
    "<=",
    defaults.maxVolatility,
    "급등락이 큰 구간보다 움직임이 과도하지 않은 구간을 보도록 제한합니다.",
    "volatility",
    {
      field: "volatility_60d_pct",
      operator: "<=",
      value: percentFromText(defaults.maxVolatility),
      unit: "percent",
    },
  ),
  condition(
    "phrase-stable-uptrend-drawdown",
    "risk",
    "고점 대비 낙폭 제한",
    "최근 고점 대비 낙폭",
    ">=",
    "-15%",
    "최근 고점에서 너무 크게 밀린 구간은 흐름이 흔들린 상태로 볼 수 있어 제한합니다.",
    "drawdown",
    {
      field: "drawdown_from_60d_high_pct",
      operator: ">=",
      value: -15,
      unit: "percent",
    },
  ),
  condition(
    "phrase-stable-uptrend-runup-cap",
    "risk",
    "급등 과열 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "안정적인 흐름이라는 표현에 맞게 짧은 기간의 과한 가격 변화를 줄입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
];

export const buildVolatilityRiskAvoidanceConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-volatility-60d-cap",
    "risk",
    "중기 변동성 제한",
    "60일 변동성",
    "<=",
    defaults.maxVolatility,
    "가격이 과도하게 흔들리는 구간을 줄이기 위한 조건입니다.",
    "volatility",
    {
      field: "volatility_60d_pct",
      operator: "<=",
      value: percentFromText(defaults.maxVolatility),
      unit: "percent",
    },
  ),
  condition(
    "phrase-intraday-range-cap",
    "risk",
    "일중 변동폭 제한",
    "20일 평균 일중 변동폭",
    "<=",
    defaults.maxIntradayRange,
    "하루 안에서 위아래 움직임이 과한 구간을 줄이기 위한 조건입니다.",
    "volatility",
    {
      field: "avg_intraday_range_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.maxIntradayRange),
      unit: "percent",
    },
  ),
  condition(
    "phrase-sharp-drop-days-cap",
    "risk",
    "급락일 수 제한",
    "최근 20일 급락일 수",
    "<=",
    defaults.maxSharpDropDays,
    "짧은 기간에 큰 하락이 자주 나온 구간을 줄이기 위한 조건입니다.",
    "volatility",
    {
      field: "sharp_drop_days_20d",
      operator: "<=",
      value: numberFromText(defaults.maxSharpDropDays),
    },
  ),
];

export const buildThemeSpeculationAvoidanceConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-theme-runup-cap",
    "risk",
    "단기 이슈 과열 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "뉴스나 테마성 움직임처럼 짧은 기간에 과하게 앞선 구간을 줄이기 위한 대체 조건입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-theme-rsi-cap",
    "risk",
    "테마성 과열 강도 완화",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "현재 MVP에는 뉴스/테마 데이터가 없어 가격 흐름 강도를 대체 지표로 사용합니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
];

export const buildFinancialDistressAvoidanceConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-management-issue-exclude",
    "stability",
    "관리 이슈 제외",
    "관리종목 여부",
    "=",
    "아님",
    "상장 유지 관련 위험 신호가 큰 회사를 줄이기 위한 조건입니다.",
    "fundamentals",
    {
      field: "is_management_issue",
      operator: "=",
      value: false,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-capital-impairment-exclude",
    "stability",
    "자본잠식 제외",
    "자본잠식 여부",
    "=",
    "아님",
    "재무 상태가 크게 훼손된 회사를 줄이기 위한 조건입니다.",
    "fundamentals",
    {
      field: "is_capital_impairment",
      operator: "=",
      value: false,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-audit-opinion-normal",
    "stability",
    "감사의견 확인",
    "감사의견 상태",
    "=",
    "정상",
    "감사의견 위험 신호가 있는 회사를 줄이기 위한 조건입니다.",
    "fundamentals",
    {
      field: "audit_opinion_status",
      operator: "=",
      value: "normal",
    },
  ),
  condition(
    "phrase-operating-loss-years-cap",
    "growth",
    "연속 적자 제한",
    "연속 영업손실 연수",
    "<=",
    "2",
    "적자가 오래 이어지는 회사를 줄이기 위한 조건입니다.",
    "fundamentals",
    {
      field: "consecutive_operating_loss_years",
      operator: "<=",
      value: 2,
    },
  ),
  condition(
    "phrase-debt-ratio-cap",
    "stability",
    "부채비율 제한",
    "부채비율",
    "<=",
    `${defaults.maxDebtRatio}%`,
    "빚 부담이 과도한 회사를 줄이기 위한 조건입니다.",
    "fundamentals",
    {
      field: "debt_ratio_pct",
      operator: "<=",
      value: numberFromText(defaults.maxDebtRatio),
      unit: "percent",
    },
  ),
];

export const buildFundamentalQualityPreferenceConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-operating-profit-positive",
    "growth",
    "영업이익 확인",
    "최근 TTM 영업이익",
    ">",
    "0",
    "본업에서 이익이 나고 있는지 확인하기 위한 조건입니다.",
    "fundamentals",
    {
      field: "operating_profit_ttm_krw",
      operator: ">",
      value: 0,
      unit: "krw",
    },
  ),
  condition(
    "phrase-revenue-positive",
    "growth",
    "매출 존재 확인",
    "최근 TTM 매출",
    ">",
    "0",
    "실제 사업 활동이 숫자로 확인되는지 보기 위한 조건입니다.",
    "fundamentals",
    {
      field: "revenue_ttm_krw",
      operator: ">",
      value: 0,
      unit: "krw",
    },
  ),
  condition(
    "phrase-quality-debt-ratio-cap",
    "stability",
    "부채 부담 제한",
    "부채비율",
    "<=",
    `${defaults.maxDebtRatio}%`,
    "재무 부담이 과도하지 않은 회사를 보기 위한 조건입니다.",
    "fundamentals",
    {
      field: "debt_ratio_pct",
      operator: "<=",
      value: numberFromText(defaults.maxDebtRatio),
      unit: "percent",
    },
  ),
  condition(
    "phrase-operating-margin-floor",
    "growth",
    "영업이익률 확인",
    "영업이익률",
    ">=",
    defaults.minOperatingMargin,
    "매출 대비 이익 체력이 너무 약하지 않은지 보기 위한 조건입니다.",
    "fundamentals",
    {
      field: "operating_margin_pct",
      operator: ">=",
      value: percentFromText(defaults.minOperatingMargin),
      unit: "percent",
    },
  ),
];

export const buildSizeLiquidityAvoidanceConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-size-market-cap-floor",
    "stability",
    "규모 하한",
    "시가총액",
    ">=",
    defaults.minMarketCap,
    "사용자가 작은 규모나 가벼운 움직임을 줄이고 싶다고 표현해 규모 기준을 추가했습니다.",
    "marketCap",
    {
      field: "market_cap_krw",
      operator: ">=",
      value: krwFromEok(defaults.minMarketCap),
      unit: "krw",
    },
  ),
  condition(
    "phrase-size-trading-value-floor",
    "liquidity",
    "거래대금 하한",
    "20일 평균 거래대금",
    ">=",
    defaults.minTradingValue,
    "거래가 너무 얇은 구간을 줄이기 위한 조건입니다.",
    "volume",
    {
      field: "avg_trading_value_20d_krw",
      operator: ">=",
      value: krwFromEok(defaults.minTradingValue),
      unit: "krw",
    },
  ),
];

export const buildDefensiveRiskPreferenceConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-defensive-volatility-cap",
    "risk",
    "변동성 완화",
    "60일 변동성",
    "<=",
    defaults.maxVolatility,
    "상대적으로 변동성이 낮은 조건으로 보기 위한 기준입니다.",
    "volatility",
    {
      field: "volatility_60d_pct",
      operator: "<=",
      value: percentFromText(defaults.maxVolatility),
      unit: "percent",
    },
  ),
  condition(
    "phrase-defensive-drawdown-cap",
    "risk",
    "낙폭 제한",
    "최근 고점 대비 낙폭",
    ">=",
    defaults.maxDefensiveDrawdown,
    "최근 고점에서 과도하게 밀린 구간을 줄이기 위한 조건입니다.",
    "drawdown",
    {
      field: "drawdown_from_60d_high_pct",
      operator: ">=",
      value: percentFromText(defaults.maxDefensiveDrawdown),
      unit: "percent",
    },
  ),
  condition(
    "phrase-defensive-runup-cap",
    "risk",
    "과열 구간 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "급하게 앞서간 구간을 줄이기 위한 조건입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-defensive-debt-ratio-cap",
    "stability",
    "재무 위험 신호 완화",
    "부채비율",
    "<=",
    `${defaults.maxDebtRatio}%`,
    "재무 위험 신호를 줄이는 조건으로 보기 위한 기준입니다.",
    "fundamentals",
    {
      field: "debt_ratio_pct",
      operator: "<=",
      value: numberFromText(defaults.maxDebtRatio),
      unit: "percent",
    },
  ),
];

export const buildEarningsQualityLowPriceReactionConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-eqlpr-revenue-growth",
    "growth",
    "매출 개선 확인",
    "최근 분기 매출 증가율",
    ">=",
    defaults.revenueGrowth,
    "실적 개선이라는 표현을 매출 증가 조건으로 변환했습니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.revenueGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-eqlpr-operating-growth",
    "growth",
    "이익 개선 확인",
    "최근 분기 영업이익 증가율",
    ">=",
    defaults.operatingGrowth,
    "이익 흐름이 나빠지지 않는지 함께 확인합니다.",
    "fundamentals",
    {
      field: "operating_profit_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.operatingGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-eqlpr-operating-profit-positive",
    "growth",
    "본업 이익 확인",
    "TTM 영업이익",
    ">",
    "0",
    "실적 개선 표현을 본업 이익이 확인되는 조건과 함께 봅니다.",
    "fundamentals",
    {
      field: "operating_profit_ttm_krw",
      operator: ">",
      value: 0,
      unit: "krw",
    },
  ),
  condition(
    "phrase-eqlpr-return-cap",
    "risk",
    "최근 과열 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "최근 가격 반응이 과하게 앞선 구간을 줄이기 위한 조건입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-eqlpr-rsi-cap",
    "risk",
    "흐름 강도 과열 완화",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "실적 표현과 함께 가격 과열 신호도 줄여 봅니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-eqlpr-bollinger-upper-cap",
    "risk",
    "밴드 상단 과열 완화",
    "종가 / 볼린저밴드 상단",
    "<=",
    "102%",
    "볼린저밴드 상단을 과하게 벗어난 구간을 줄입니다.",
    "bollingerBand",
    {
      field: "close_to_bollinger_upper_pct",
      operator: "<=",
      value: 102,
      unit: "percent",
    },
  ),
];

export const buildValueWithTechnicalConfirmationConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-value-tech-per-cap",
    "valuation",
    "PER 부담 확인",
    "PER",
    "<=",
    defaults.maxPer,
    "실적 대비 가격 부담이 과하지 않은지 확인합니다.",
    "valuation",
    {
      field: "per",
      operator: "<=",
      value: numberFromText(defaults.maxPer),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-value-tech-pbr-cap",
    "valuation",
    "PBR 부담 확인",
    "PBR",
    "<=",
    defaults.maxPbr,
    "자산 대비 가격 부담이 과하지 않은지 확인합니다.",
    "valuation",
    {
      field: "pbr",
      operator: "<=",
      value: numberFromText(defaults.maxPbr),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-value-tech-roe-floor",
    "valuation",
    "ROE 확인",
    "ROE",
    ">=",
    defaults.minRoe,
    "가격 부담만 낮은 것이 아니라 자기자본 효율도 함께 확인합니다.",
    "valuation",
    {
      field: "roe_pct",
      operator: ">=",
      value: percentFromText(defaults.minRoe),
      unit: "percent",
    },
  ),
  condition(
    "phrase-value-tech-ma-alignment",
    "trend",
    "차트 흐름 확인",
    "20일 이동평균선",
    ">=",
    "60일 이동평균선",
    "밸류 부담과 함께 차트 흐름이 완전히 훼손되지 않았는지 확인합니다.",
    "movingAverageAlignment",
    { field: "ma20", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-value-tech-close-above-60ma",
    "trend",
    "중기선 회복 확인",
    "종가",
    ">=",
    "60일 이동평균선",
    "가격이 중기 기준선 아래에만 머물러 있는 구간을 줄입니다.",
    "movingAverage",
    { field: "close", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-value-tech-no-new-low",
    "risk",
    "신저가 이탈 완화",
    "60일 신저가",
    "=",
    "아님",
    "최근 저점을 새로 낮춘 구간을 줄입니다.",
    "highLowBreakout",
    {
      field: "is_60d_new_low",
      operator: "=",
      value: false,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-value-tech-volume-recovery",
    "liquidity",
    "거래 회복 확인",
    "5일 평균 거래량 / 20일 평균 거래량",
    ">=",
    "100%",
    "차트 흐름과 함께 거래가 완전히 말라 있지 않은지 확인합니다.",
    "volume",
    {
      field: "avg_volume_5d_to_20d_pct",
      operator: ">=",
      value: 100,
      unit: "percent",
    },
  ),
];

export const buildRevenueGrowthConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-revenue-growth-quarter",
    "growth",
    "분기 매출 성장",
    "최근 분기 매출 YoY 증가율",
    ">=",
    defaults.revenueGrowth,
    "외형 성장 표현을 최근 분기 매출 증가 조건으로 변환했습니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.revenueGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-revenue-growth-ttm",
    "growth",
    "TTM 매출 성장",
    "TTM 매출 증가율",
    ">=",
    defaults.revenueGrowth,
    "최근 한 해 기준 매출 흐름도 함께 확인합니다.",
    "fundamentals",
    {
      field: "revenue_growth_ttm_pct",
      operator: ">=",
      value: percentFromText(defaults.revenueGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-revenue-growth-trend",
    "growth",
    "매출 추세 확인",
    "최근 4분기 매출 증가 추세",
    "=",
    "확인",
    "매출이 한 번만 튄 것이 아니라 이어지는지 확인합니다.",
    "fundamentals",
    {
      field: "is_revenue_growth_trend_4q",
      operator: "=",
      value: true,
      unit: "boolean",
    },
  ),
];

export const buildProfitGrowthConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-profit-growth-operating",
    "growth",
    "영업이익 성장",
    "최근 분기 영업이익 증가율",
    ">=",
    defaults.operatingGrowth,
    "이익 개선 표현을 영업이익 증가 조건으로 변환했습니다.",
    "fundamentals",
    {
      field: "operating_profit_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.operatingGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-profit-growth-net-income",
    "growth",
    "순이익 성장",
    "최근 분기 순이익 증가율",
    ">=",
    defaults.operatingGrowth,
    "순이익 흐름도 함께 확인합니다.",
    "fundamentals",
    {
      field: "net_income_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.operatingGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-profit-margin-improvement",
    "growth",
    "수익성 개선",
    "영업이익률 변화",
    ">",
    "0%",
    "이익률이 개선되는지 확인합니다.",
    "fundamentals",
    {
      field: "operating_margin_change_yoy_pct",
      operator: ">",
      value: 0,
      unit: "percent",
    },
  ),
  condition(
    "phrase-profit-ttm-positive",
    "growth",
    "본업 이익 확인",
    "TTM 영업이익",
    ">",
    "0",
    "최근 기준으로 본업 이익이 확인되는지 봅니다.",
    "fundamentals",
    {
      field: "operating_profit_ttm_krw",
      operator: ">",
      value: 0,
      unit: "krw",
    },
  ),
];

export const buildValuationBurdenLowConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-valuation-burden-per-cap",
    "valuation",
    "PER 부담 제한",
    "PER",
    "<=",
    defaults.maxPer,
    "실적 대비 가격 부담이 과하지 않은지 확인합니다.",
    "valuation",
    {
      field: "per",
      operator: "<=",
      value: numberFromText(defaults.maxPer),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-valuation-burden-pbr-cap",
    "valuation",
    "PBR 부담 제한",
    "PBR",
    "<=",
    defaults.maxPbr,
    "자산 대비 가격 부담이 과하지 않은지 확인합니다.",
    "valuation",
    {
      field: "pbr",
      operator: "<=",
      value: numberFromText(defaults.maxPbr),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-valuation-burden-return-cap",
    "risk",
    "최근 가격 과열 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "최근 가격이 너무 앞서간 구간을 줄입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-valuation-burden-rsi-cap",
    "risk",
    "RSI 과열 완화",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "가격 흐름 강도가 과하게 높은 구간을 줄입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-valuation-burden-high-proximity",
    "risk",
    "신고가 근접 위험 완화",
    "60일 고점 대비 위치",
    "<=",
    "95%",
    "최근 고점에 너무 가까운 구간은 가격 부담 위험으로 표시하기 위한 대체 조건입니다.",
    "highLowBreakout",
    {
      field: "close_to_60d_high_pct",
      operator: "<=",
      value: 95,
      unit: "percent",
    },
  ),
];

export const buildUnderTheRadarQualityConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-under-radar-revenue-growth",
    "growth",
    "실적 개선 확인",
    "최근 분기 매출 증가율",
    ">=",
    defaults.revenueGrowth,
    "내용이 좋아지는 표현을 실적 개선 조건으로 변환했습니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.revenueGrowth),
      unit: "percent",
    },
  ),
  condition(
    "phrase-under-radar-operating-profit",
    "growth",
    "본업 이익 확인",
    "TTM 영업이익",
    ">",
    "0",
    "실적 기반이 확인되는지 함께 봅니다.",
    "fundamentals",
    {
      field: "operating_profit_ttm_krw",
      operator: ">",
      value: 0,
      unit: "krw",
    },
  ),
  condition(
    "phrase-under-radar-return-cap",
    "risk",
    "가격 반응 과열 완화",
    "20일 상승률",
    "<=",
    defaults.recentReturnCap,
    "시장 관심도가 아직 높지 않은 조건으로 중립화하기 위해 최근 가격 과열을 줄입니다.",
    "recentReturn",
    {
      field: "return_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.recentReturnCap),
      unit: "percent",
    },
  ),
  condition(
    "phrase-under-radar-volume-cap",
    "liquidity",
    "거래 관심 과열 완화",
    "당일 거래량 / 20일 평균 거래량",
    "<=",
    defaults.volumeSpike,
    "뉴스/검색량 데이터가 없어 거래량 과열 여부를 대체 조건으로 사용합니다.",
    "volume",
    {
      field: "volume_today_to_avg_20d_pct",
      operator: "<=",
      value: percentFromText(defaults.volumeSpike),
      unit: "percent",
    },
  ),
];

export const buildTurnaroundRecoveryConditions = (
  defaults: ProfileDefaults,
) => [
  condition(
    "phrase-turnaround-operating-profit-change",
    "growth",
    "흑자전환 확인",
    "영업이익 흑자전환 여부",
    "=",
    "확인",
    "적자에서 흑자로 돌아서는 회복 신호를 확인합니다.",
    "fundamentals",
    {
      field: "is_operating_profit_turnaround",
      operator: "=",
      value: true,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-turnaround-margin-improvement",
    "growth",
    "이익률 개선 확인",
    "영업이익률 변화",
    ">",
    "0%",
    "수익성이 개선되는지 함께 확인합니다.",
    "fundamentals",
    {
      field: "operating_margin_change_yoy_pct",
      operator: ">",
      value: 0,
      unit: "percent",
    },
  ),
  condition(
    "phrase-turnaround-revenue-recovery",
    "growth",
    "매출 회복 확인",
    "최근 분기 매출 증가율",
    ">=",
    "0%",
    "매출이 더 악화되는 구간을 줄이고 회복 신호를 확인합니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: 0,
      unit: "percent",
    },
  ),
  condition(
    "phrase-turnaround-operating-recovery",
    "growth",
    "영업이익 회복 확인",
    "최근 분기 영업이익 증가율",
    ">=",
    defaults.operatingGrowth,
    "영업이익의 회복 흐름을 확인합니다.",
    "fundamentals",
    {
      field: "operating_profit_growth_recent_quarter_pct",
      operator: ">=",
      value: percentFromText(defaults.operatingGrowth),
      unit: "percent",
    },
  ),
];

export const buildValueTrapAvoidanceConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-value-trap-per-cap",
    "valuation",
    "PER 부담 확인",
    "PER",
    "<=",
    defaults.maxPer,
    "낮은 밸류 부담 조건을 확인합니다.",
    "valuation",
    {
      field: "per",
      operator: "<=",
      value: numberFromText(defaults.maxPer),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-value-trap-pbr-cap",
    "valuation",
    "PBR 부담 확인",
    "PBR",
    "<=",
    defaults.maxPbr,
    "자산 대비 가격 부담이 과하지 않은지 확인합니다.",
    "valuation",
    {
      field: "pbr",
      operator: "<=",
      value: numberFromText(defaults.maxPbr),
      unit: "ratio",
    },
  ),
  condition(
    "phrase-value-trap-close-above-60ma",
    "trend",
    "중기선 회복 확인",
    "종가",
    ">=",
    "60일 이동평균선",
    "계속 빠지는 흐름을 줄이기 위해 중기 기준선 회복 여부를 봅니다.",
    "movingAverage",
    { field: "close", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-value-trap-volume-recovery",
    "liquidity",
    "거래 회복 확인",
    "5일 평균 거래량 / 20일 평균 거래량",
    ">=",
    "100%",
    "장기 소외 위험을 줄이기 위해 거래가 완전히 말라 있지 않은지 확인합니다.",
    "volume",
    {
      field: "avg_volume_5d_to_20d_pct",
      operator: ">=",
      value: 100,
      unit: "percent",
    },
  ),
  condition(
    "phrase-value-trap-no-new-low",
    "risk",
    "신저가 이탈 완화",
    "60일 신저가",
    "=",
    "아님",
    "저점이 계속 낮아지는 구간을 줄입니다.",
    "highLowBreakout",
    {
      field: "is_60d_new_low",
      operator: "=",
      value: false,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-value-trap-revenue-check",
    "growth",
    "실적 동반 확인",
    "최근 분기 매출 증가율",
    ">=",
    "0%",
    "밸류 부담만 낮은 것이 아니라 실적이 더 악화되는 구간을 줄입니다.",
    "fundamentals",
    {
      field: "revenue_growth_recent_quarter_pct",
      operator: ">=",
      value: 0,
      unit: "percent",
    },
  ),
];

export const buildBrokenChartExclusionConditions = () => [
  condition(
    "phrase-close-above-60ma",
    "trend",
    "중기선 하회 제외",
    "종가",
    ">=",
    "60일 이동평균선",
    "중기 흐름 기준선 아래로 내려간 구간을 줄입니다.",
    "movingAverage",
    { field: "close", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-no-new-low",
    "risk",
    "최근 저점 이탈 제외",
    "60일 신저가",
    "=",
    "아님",
    "최근 저점을 새로 낮춘 구간을 제외하는 조건입니다.",
    "highLowBreakout",
    {
      field: "is_60d_new_low",
      operator: "=",
      value: false,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-not-reverse-alignment",
    "trend",
    "역배열 제외",
    "20일 이동평균선",
    ">=",
    "60일 이동평균선",
    "단기와 중기 흐름이 완전히 아래로 정렬된 상태를 줄입니다.",
    "movingAverageAlignment",
    { field: "ma20", operator: ">=", value: "ma60" },
  ),
];

export const buildPullbackConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-pullback-trend",
    "trend",
    "중기 추세 유지",
    "20일 이동평균선",
    ">=",
    "60일 이동평균선",
    "중기 흐름은 유지되는지 확인합니다.",
    "movingAverageAlignment",
    { field: "ma20", operator: ">=", value: "ma60" },
  ),
  condition(
    "phrase-pullback-short-rest",
    "trend",
    "단기 조정",
    "5일 가격 변화율",
    "between",
    defaults.pullbackReturnRange,
    "단기적으로 쉬어 가는 상태를 수치 범위로 표현합니다.",
    "pullback",
    {
      field: "return_5d_pct",
      operator: "between",
      ...rangeFromText(defaults.pullbackReturnRange),
      unit: "percent",
    },
  ),
  condition(
    "phrase-pullback-rsi-neutral",
    "risk",
    "RSI 중립 구간",
    "RSI(14)",
    "between",
    defaults.pullbackRsiRange,
    "과하게 식거나 과하게 뜨거운 상태를 피하기 위한 보조 조건입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "between",
      ...rangeFromText(defaults.pullbackRsiRange),
      unit: "ratio",
    },
  ),
];

export const buildThreeWhiteSoldiersConditions = (defaults: ProfileDefaults) => [
  condition(
    "phrase-three-white-soldiers",
    "trend",
    "적삼병 패턴",
    "최근 3거래일 캔들",
    "=",
    "양봉 연속",
    "짧은 기간에 캔들 흐름이 이어지는지 확인합니다.",
    "threeWhiteSoldiers",
    {
      field: "is_three_white_soldiers",
      operator: "=",
      value: true,
      unit: "boolean",
    },
  ),
  condition(
    "phrase-three-white-rsi",
    "risk",
    "패턴 과열 제한",
    "RSI(14)",
    "<=",
    defaults.rsiCeiling,
    "패턴이 나타나더라도 흐름 강도가 과한 구간은 줄입니다.",
    "rsi",
    {
      field: "rsi_14",
      operator: "<=",
      value: numberFromText(defaults.rsiCeiling),
      unit: "ratio",
    },
  ),
];
